# Generated by Django 5.1 on 2024-09-05 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=200, null=True)),
                ("cat_discription", models.CharField(max_length=200)),
                ("cat_salary", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="customer_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_name", models.CharField(max_length=200)),
                ("cust_contact", models.CharField(max_length=200)),
                ("cust_address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="employee_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=200)),
                ("emp_address", models.CharField(max_length=200)),
                ("emp_contact", models.CharField(max_length=200)),
                ("emp_image", models.FileField(null=True, upload_to="")),
                ("emp_dob", models.CharField(max_length=200)),
                ("emp_gender", models.CharField(max_length=200)),
                ("face_encoding", models.BinaryField()),
                (
                    "categoryid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=200)),
                ("log_type", models.CharField(max_length=200)),
                (
                    "attend_of",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.employee_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="service_done",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=200)),
                ("amount", models.CharField(max_length=200)),
                (
                    "cust_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.customer_details",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.employee_details",
                    ),
                ),
            ],
        ),
    ]
